module.exports = grammar({
  name: 'solar',
  extras: $ => [$.comment, /[ \t\r\n\f\uFEFF\u2060\u200B]+/],
  conflicts: $ => [
    [$._expression, $.identifier_path],
    [$._expression, $.struct_literal],
    [$.identifier_path],
    ['return_statement']
  ],
  word: $ => $.identifier,
  rules: {
    source_file: $ => repeat(choice($._simple_statement, $._compound_statement)),
    _compound_statement: $ => choice($.function_definition, $.object_definition, $.impl_definition, $.enum_definition, $.if_statement, $.while_statement),
    _simple_statement: $ => choice($.variable_declaration, $.assignment_statement, $.compound_assignment_statement, $.return_statement, $.use_declaration, $.rust_dependency, $.expression_statement),
    rust_dependency: $ => seq('rust', 'dependency', $.identifier, '=', $.string),
    function_definition: $ => seq(repeat($.attribute), repeat(choice('async', 'const', 'pub', 'unsafe')), 'fn', $.identifier, optional($.type_parameters), $.parameters, optional(seq('->', $.type)), ':', $.block),
    object_definition: $ => seq(repeat($.attribute), 'obj', $.identifier, optional($.type_parameters), ':', $.block),
    impl_definition: $ => seq('impl', optional($.type_parameters), $.type, optional(seq('for', $.type)), ':', $.block),
    enum_definition: $ => seq(repeat($.attribute), 'enum', $.identifier, optional($.type_parameters), ':', $.block),
    variant_definition: $ => seq(repeat($.attribute), $.identifier, optional(seq('(', commaSep1($.type), ')'))),
    use_declaration: $ => seq('use', $.identifier_path),
    type_parameters: $ => seq('<', commaSep1($.identifier), '>'),
    parameters: $ => seq('(', commaSep($.parameter), ')'),
    parameter: $ => choice(seq(optional('mut'), $.identifier, optional(seq(':', $.type))), $.self_parameter),
    self_parameter: $ => seq(optional(choice('&', seq('&', 'mut'))), 'self'),
    type: $ => choice($.identifier_path, seq('&', optional('mut'), $.type), seq('*', $.type), seq('[', $.type, ';', $.number, ']'), seq('(', ')')),
    identifier_path: $ => seq($.identifier, repeat(seq('::', choice($.identifier, '*')))),
    block: $ => seq(repeat1(choice($._simple_statement, $._compound_statement))),
    variable_declaration: $ => seq('var', optional('mut'), $.identifier, optional(seq(':', $.type)), optional(seq('=', $._expression))),
    assignment_statement: $ => seq($._expression, '=', $._expression),
    compound_assignment_statement: $ => seq($._expression, choice('+=', '-=', '*=', '/='), $._expression),
    if_statement: $ => seq('if', $._expression, ':', $.block, optional(seq('else', optional(':'), $.block))),
    while_statement: $ => seq('while', $._expression, ':', $.block),
    return_statement: $ => seq('return', optional($._expression)),
    expression_statement: $ => $._expression,
    _expression: $ => choice($.identifier_path, $.number, $.string, $.boolean, $.binary_expression, $.unary_expression, $.call_expression, $.macro_call_expression, $.method_call_expression, $.member_access_expression, $.index_expression, $.parenthesized_expression, $.struct_literal, $.as_expression, $.await_expression),
    as_expression: $ => prec.left(25, seq($._expression, 'as', $.type)),
    await_expression: $ => prec(40, seq($._expression, '.', 'await')),
    binary_expression: $ => choice(...[['+',10], ['-',10], ['*',20], ['/',20], ['==',5], ['!=',5], ['>',5], ['<',5], ['>=',5], ['<=',5]].map(([op, p]) => prec.left(p, seq($._expression, op, $._expression)))),
    unary_expression: $ => prec(30, seq(choice('-', '*', '&', seq('&', 'mut')), $._expression)),
    call_expression: $ => prec(40, seq($.identifier_path, '(', commaSep($._expression), ')')),
    macro_call_expression: $ => prec(40, seq($.identifier_path, '!', '(', commaSep($._expression), ')')),
    method_call_expression: $ => prec(40, seq($._expression, '.', $.identifier, '(', commaSep($._expression), ')')),
    member_access_expression: $ => prec(40, seq($._expression, '.', choice($.identifier, $.number))),
    index_expression: $ => prec(40, seq($._expression, '[', $._expression, ']')),
    parenthesized_expression: $ => seq('(', $._expression, ')'),
    struct_literal: $ => seq($.identifier_path, '{', commaSep($.struct_field), '}'),
    struct_field: $ => seq($.identifier, optional(seq(':', $._expression))),
    identifier: $ => /[a-zA-Z_][a-zA-Z0-9_]*/,
    number: $ => /\d+(\.\d+)?/,
    string: $ => /"([^"\\]|\\.)*"/,
    boolean: $ => choice('true', 'false'),
    attribute: $ => seq('#', '[', $._expression, ']'),
    comment: $ => seq('//', /.*/)
  }
});
function commaSep(rule) { return optional(commaSep1(rule)); }
function commaSep1(rule) { return seq(rule, repeat(seq(',', rule))); }
